export const surveySchema = [
  {
    id: 'q1',
    question: 'What is your full name?',
    type: 'text',
    required: true,
  },
  {
    id: 'q2',
    question: 'What is your age?',
    type: 'text',
    required: true,
  },
  {
    id: 'q3',
    question: 'What is your gender?',
    type: 'radio',
    options: ['Male', 'Female', 'Other'],
    required: true,
  },
  {
    id: 'q4',
    question: 'Which programming languages do you know?',
    type: 'checkbox',
    options: ['JavaScript', 'Python', 'Java', 'C++', 'Go', 'Rust'],
    required: false,
  },
  {
    id: 'q5',
    question: 'What is your favorite sport?',
    type: 'radio',
    options: ['Football', 'Cricket', 'Basketball', 'Tennis', 'Other'],
    required: true,
  },
  {
    id: 'q6',
    question: 'Which sports do you play regularly?',
    type: 'checkbox',
    options: ['Football', 'Cricket', 'Badminton', 'Table Tennis', 'Running'],
    required: true,
  },
  {
    id: 'q7',
    question: 'Who is your favorite cricketer?',
    type: 'text',
    required: false,
  },
  {
    id: 'q8',
    question: 'Do you follow the Olympics?',
    type: 'radio',
    options: ['Yes', 'No', 'Sometimes'],
    required: true,
  },
  {
    id: 'q9',
    question: 'Which team do you support in football?',
    type: 'text',
    required: false,
  },
  {
    id: 'q10',
    question: 'Which fitness activities do you enjoy?',
    type: 'checkbox',
    options: ['Gym', 'Yoga', 'Cycling', 'Swimming', 'None'],
    required: false,
  },
  {
    id: 'q11',
    question: 'How often do you play sports per week?',
    type: 'radio',
    options: ['0', '1-2', '3-5', '6+'],
    required: true,
  },
  {
    id: 'q12',
    question: 'Do you prefer indoor or outdoor sports?',
    type: 'radio',
    options: ['Indoor', 'Outdoor', 'Both'],
    required: true,
  },
  {
    id: 'q13',
    question: 'Which Olympic sports do you watch?',
    type: 'checkbox',
    options: ['Athletics', 'Swimming', 'Gymnastics', 'Shooting', 'Wrestling'],
    required: false,
  },
  {
    id: 'q14',
    question: 'Do you follow IPL?',
    type: 'radio',
    options: ['Yes', 'No', 'Sometimes'],
    required: true,
  },
  {
    id: 'q15',
    question: 'Which IPL team do you support?',
    type: 'text',
    required: false,
  },
  {
    id: 'q16',
    question: 'Do you participate in local tournaments?',
    type: 'radio',
    options: ['Yes', 'No'],
    required: false,
  },
  {
    id: 'q17',
    question: 'Your dream sports destination?',
    type: 'text',
    required: false,
  },
  {
    id: 'q18',
    question: 'Which sports celebrities do you follow on social media?',
    type: 'text',
    required: false,
  },
  {
    id: 'q19',
    question: 'How do you stay updated on sports news?',
    type: 'checkbox',
    options: ['TV', 'YouTube', 'Twitter', 'News apps', 'Newspapers'],
    required: true,
  },
  {
    id: 'q20',
    question: 'Any suggestions for improving sports facilities in your area?',
    type: 'text',
    required: false,
  },
];
